# =============================================================================
# Ansible Inventory
# =============================================================================
# Defines the target hosts for configuration management.
# For this local development setup, we target localhost.
# =============================================================================

[ec2_server]
13.51.199.107 ansible_user=ubuntu ansible_ssh_private_key_file=~/Downloads/Mad-Trip.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ec2_server:vars]
# Project-specific variables
project_name=ai-devops-pipeline
minikube_profile=devops-cluster
app_namespace=devops-project
monitoring_namespace=monitoring